In [3]:
# CELL 1 – IMPORT & ĐỌC DỮ LIỆU

import pandas as pd
import numpy as np
import os

df = pd.read_csv("../data_merge/order_full_merged.csv")

print("DỮ LIỆU ĐẦU VÀO:")
display(df.head())

DỮ LIỆU ĐẦU VÀO:

,order_id,product_id,order_time,qty,product_name,price,unit_cost,revenue,profit
0,OD2002,CF03,2024-01-01 14:12:00,2.0,Bac Xiu,35000.0,NaN,70000.0,NaN
1,OD2003,CF03,2024-01-01 06:16:00,2.0,Bac Xiu,35000.0,NaN,70000.0,NaN
2,OD2004,CF02,2024-01-01 04:55:00,1.0,Ca Phe Sua,35000.0,15000.0,35000.0,20000.0
3,OD2006,CF02,2024-01-01 06:56:00,3.0,Ca Phe Sua,35000.0,15000.0,105000.0,20000.0
4,OD2009,CF06,NaN,1.0,Matcha Latte,35000.0,9000.0,35000.0,26000.0

In [4]:
# CELL 2 – DOANH THU THEO SẢN PHẨM

revenue_by_product = (
    df.groupby(["product_id", "product_name"])
      .agg(
          total_qty=("qty", "sum"),
          total_revenue=("revenue", "sum")
      )
      .reset_index()
      .sort_values("total_revenue", ascending=False)
)

print("DOANH THU THEO SẢN PHẨM:")
display(revenue_by_product)

DOANH THU THEO SẢN PHẨM:

  product_id  product_name  total_qty  total_revenue
3       CF04       Tra Dao       33.0      1485000.0
1       CF02    Ca Phe Sua       30.0      1050000.0
2       CF03      Bac  Xiu       22.0       770000.0
0       CF01    Ca Phe Den       16.0       720000.0
5       CF06  Matcha Latte       19.0       665000.0
4       CF05  Sinh To Xoai       22.0          660.0

In [ ]:
# CELL 3 – LỢI NHUẬN THEO SẢN PHẨM

profit_by_product = (
    df.groupby(["product_id", "product_name"])
      .agg(
          avg_profit=("profit", "mean"),
          unit_cost=("unit_cost", "mean"),
          price=("price", "mean")
      )
      .reset_index()
      .sort_values("avg_profit", ascending=False)
)

print("LỢI NHUẬN TRUNG BÌNH THEO SẢN PHẨM:")
display(profit_by_product)